/// Flutter icons Radio_App
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Radio_App
///      fonts:
///       - asset: fonts/Radio_App.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Radio_App {
  Radio_App._();

  static const _kFontFam = 'Radio_App';

  static const IconData advertisers = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData presenters = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData website = const IconData(0xe80b, fontFamily: _kFontFam);
}
